"""hola3

Revision ID: c1d46bd9777f
Revises: 142f6023cfd1
Create Date: 2023-03-17 23:01:09.376920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d46bd9777f'
down_revision = '142f6023cfd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('productos_categforia_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categorias', ['categoria_id'], ['id'])
        batch_op.drop_column('categforia_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categforia_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('productos_categforia_id_fkey', 'categorias', ['categforia_id'], ['id'])
        batch_op.drop_column('categoria_id')

    # ### end Alembic commands ###
