"""tambien nombre columna

Revision ID: e389caa25098
Revises: c0e44dd7df5c
Create Date: 2023-03-16 20:25:48.351942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e389caa25098'
down_revision = 'c0e44dd7df5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.Text(), nullable=False))
        batch_op.drop_column('pasword')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pasword', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
