# Generated by Django 4.1.7 on 2023-03-31 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_cree_tabla_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
